name: _build-materials (reusable)

on:
  workflow_call:
    inputs:
      mktarget:
        description: 'Make target to run'
        type: string
        required: true
      pandoc_data:
        description: 'Temporary folder for Pandoc filters: Will be overwritten!'
        default: '.pandoc'
        type: string
        required: false
      metadata:
        description: 'Metadata file (.yaml)'
        type: string
        required: true
      book_src:
        description: 'Name of book.md'
        default: 'book.md'
        type: string
        required: false
      build_dir:
        description: 'Prefix for output, also name for target orphan branch'
        type: string
        required: true
      image_dark_suffix:
        description: 'Suffix for inverted images (dark mode)'
        default: '_inv'
        type: string
        required: false
      publish:
        description: 'shall we push results to orphan branch'
        type: boolean
        required: false
        default: true
    secrets: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lecture-repo (fully)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build materials
        uses: cagix/pandoc-lecture-zen@master
        with:
          mktarget: ${{ inputs.mktarget }}
          pandoc_data: ${{ inputs.pandoc_data }}
          metadata: ${{ inputs.metadata }}
          book_src: ${{ inputs.book_src }}
          build_dir: ${{ inputs.build_dir }}
          image_dark_suffix: ${{ inputs.image_dark_suffix }}

      - name: Upload build artifact
        if: ${{ inputs.publish }}
        uses: actions/upload-artifact@v7
        with:
          name: materials-${{ inputs.build_dir }}
          path: ${{ inputs.build_dir }}
          overwrite: true
          retention-days: 1

      - name: Check/Debug
        run: |
          ls -lags
          ls -lags "${{ inputs.build_dir }}"

  publish:
    if: ${{ inputs.publish }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout lecture-repo (last commit)
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          clean: true

      - name: Retrieve last commit message
        id: message
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            msg="publish materials (manual trigger)"
          else
            msg="$(git log -n 1 --pretty=format:'%s' 2>/dev/null || echo 'unversioned')"
            msg=${msg//\"/}
            msg=${msg//\'/}
            msg=${msg//\`/}
            msg=${msg//\$/}
          fi
          echo "COMMIT_MESSAGE=$msg" >> "$GITHUB_OUTPUT"

      - name: Create new orphan branch
        run: |
          git reset --hard
          git clean -fd
          git branch -D "${{ inputs.build_dir }}" 2>/dev/null || true
          git switch --orphan "${{ inputs.build_dir }}"
          git rm -r --cached . || true

      - name: Clean working tree
        run: |
          find . -mindepth 1 -maxdepth 1  \
            ! -name '.git'                \
            -exec rm -rf {} +

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: materials-${{ inputs.build_dir }}
          path: ${{ inputs.build_dir }}

      - name: Copy files over
        run: |
          mv "${{ inputs.build_dir }}"/* .
          rm -rf "${{ inputs.build_dir }}"

      - name: Commit and push
        env:
          COMMIT_MESSAGE: ${{ steps.message.outputs.COMMIT_MESSAGE }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "cagix"
            git config user.email "cagix@users.noreply.github.com"

            git add -f .
            git commit -m "$COMMIT_MESSAGE"
            git push --force origin "${{ inputs.build_dir }}"
          else
            echo "no changes to push"
          fi

      - name: Delete build artifact
        if: ${{ success() }}
        uses: actions/github-script@v8
        with:
          script: |
            const artifactName = 'materials-${{ inputs.build_dir }}';
            const { owner, repo } = context.repo;
            const run_id = context.runId;

            const { data } = await github.rest.actions.listWorkflowRunArtifacts({ owner, repo, run_id });
            const matches = data.artifacts.filter(a => a.name === artifactName);

            if (matches.length === 0) {
              core.info(`No artifact found in this run named ${artifactName}`);
              return;
            }

            for (const a of matches) {
              core.info(`Deleting (this run) ${a.name} (id=${a.id})`);
              await github.rest.actions.deleteArtifact({ owner, repo, artifact_id: a.id });
            }

      - name: Check/Debug
        run: |
          ls -lags
