name: Beamer Slides

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build-materials.yaml
    with:
      mktarget: beamer
      publish_branch: _beamer
