name: TESTS

on:
  # triggered by pull requests
  pull_request:
  # triggered manually
  workflow_dispatch:

jobs:
  # try building slides (pandoc, beamer)
  test_beamer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  # try building lecture notes (gfm)
  test_gfm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-lecture-zen@master
        with:
          mktarget: gfm
          pandoc_data: .pandoc
          metadata: cb.yaml
          publish_dir: _gfm

  # try building lecture notes (pdf)
  test_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-lecture-zen@master
        with:
          mktarget: pdf
          pandoc_data: .pandoc
          metadata: cb.yaml
          publish_dir: _pdf
